### PR TITLE
with_mock_dir should prefer tests/testthat

### PR DESCRIPTION
**Pull request by nealrichardson**
cc @maelle, any thoughts on this?

### CODE REVIEW

**Comment by maelle** [comment]
why not use `testthat::test_path()`?

**Comment by maelle** [comment]
(but in any case I do like the improvement, it'll be useful for debugging I think!)

**Comment by nealrichardson** [comment]
> why not use `testthat::test_path()`?

It could work, though it's more restrictive. It requires paths to be inside `tests/testthat` and can error. It wasn't suitable for `.mockPaths()` for those reasons, but maybe it would be ok in this case?

**Comment by maelle** [comment]
Ah right, could there be use cases of with_mock_dir() outside of tests? 🤔

**Comment by nealrichardson** [comment]
I'm not sure, but if we can support both interactive testing _and_ using it outside of tests, IMO it's worth a shot. I'll merge this and we can switch to test_path later if we find a reason to.

**Pull request merged**
