### PR TITLE
Fix CRLF issue on GHA

### PR DESCRIPTION
**Pull request by nealrichardson**
I've gotten rid of the `\r\n` mess and the strings look visually the same but for some reason they're still not testing as identical. Will have to debug further.

FYI @jonkeane

### CODE REVIEW

**Comment by jonkeane** [comment]
Welcome to my world! 🙃 I did a bunch of feeling around in the dark to find a difference, I even tried the large hammer of `gsub("[ \t\r\n\\h\\v]", "", content(...))` and still there was some mysterious difference that made the strings different.

**Comment by nealrichardson** [comment]
Doing some spelunking with waldo and cleaning up the output, I now see

```
old[168:174] vs new[168:174]
  "                                //operationsSorter: \\"alpha\\","
  "                                presets: ["
  "                                    SwaggerUIBundle.presets.apis,"
- "                                    // yay ES6 modules <U+2198>"
+ "                                    // yay ES6 modules <U+2198>"
  "                                    Array.isArray(SwaggerUIStandalonePreset) ? SwaggerUIStandalonePreset : SwaggerUIStandalonePreset.default"
  "                                ],"
  "                                plugins: ["
```

image

which confirms that somehow this is a windows unicode issue (and extra annoying that this is choking on (1) a code comment (2) in javascript (3) with a gratuitous special character (4) to express excitement about some ES6 hotness).

**Comment by nealrichardson** [comment]
Fixed! PTAL @jonkeane. Not sure if all of the UTF-8 encoding everywhere is necessary but it shouldn't hurt. Doing the string comparison after converting to native encoding though was the change that made the test pass in the end (after switching to a binary file connection to stop the CRLF conversion).

**Comment by jonkeane** [comment]
Looks good to me (and looks like you also ran into curl not installing for 3.3 on ubuntu as well? I hard coded it, but this is definitely better)

**Comment by nealrichardson** [comment]
> Looks good to me (and looks like you also ran into curl not installing for 3.3 on ubuntu as well? I hard coded it, but this is definitely better)

yeah, I'm guessing this is in the r-lib/actions workflow template because you added it when you added GHA, but I deleted it (foolishly) because hey, `httptest` doesn't have system dependencies 🤦

**Pull request merged**
